config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ('/')
  root "courses#index"
  get "pages/about", to: "pages#about"
  get "pages/contact", to: "pages#contact"
  get "pages/address", to: "pages#address"

  resources :courses
  resources :students

  get "login", to: "logins#new"
  post "login", to: "logins#create"
  delete "logout", to: "logins#destroy"

  post "courses_enroll", to: "student_courses#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  validates :short_name, presence: true
  validates :name, presence: true, length: { minimum: 6, maximum: 100 }
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  VALID_EMAIL_REGEX = VALID_EMAIL_REGEX = /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/
  validates :name, presence: true, length: { minimum: 4, maximum: 30 }
  validates :email, presence: true, length: { maximum: 100 },
            uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :require_user

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] ="You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [ :show, :edit, :update, :destroy ]
  skip_before_action :require_user, only: [ :index ]
  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = "Course added successfully"
      redirect_to root_path
    else
      flash[:error] = "Something went wrong !!"
      render :new
    end
  end

  def index
    @courses = Course.all
  end

  def show
  end

  def update
    if @course.update(course_params)
      flash[:notice] = "Course details updated successfully"
      redirect_to @course
    else
      flash[:error] = "Something went wrong !!"
      redirect_to :edit
    end
  end

  def destroy
    if @course.destroy
      flash[:notice] = "Course deleted successfully"
      redirect_to root_path
    else
      flash[:error] = "Something went wrong !!"
      redirect_to @course
    end
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:short_name, :name, :description)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :require_user, only: [ :new, :create ]
  def new
  end

  def create
    @student = Student.find_by(email: params[:login][:email])
    if @student && @student.authenticate(params[:login][:password])
      session[:student_id] = @student.id
      flash[:success] = "You have successfully logged in"
      redirect_to courses_path
    else
      flash[:error] = "Your credentials are not correct"
      render :new
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = "logged out!!"
    redirect_to login_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def address
  end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  def create
    course_to_add = Course.find(params[:course_id])
    unless current_user.courses.include?(course_to_add)
      StudentCourse.create(course: course_to_add, student: current_user)
      flash[:notice] = "You successfully enrolled in #{course_to_add.short_name}"
      redirect_to current_user
    else
      flash[:error] = "Something went wrong with your enrollment"
      redirect_to courses
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, except: [ :index, :new, :create ]
  before_action :require_same_user, only: [ :edit, :update ]
  skip_before_action :require_user, only: [ :index, :show, :create ]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)
    if @student.save
      redirect_to @student
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to @student
    else
      render "edit"
    end
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def require_same_user
      if current_user != @student
        flash[:notice] = "You can edit your own profile only"
        redirect_to root_path
      end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_courses_list.html.erb
<% @courses.each do |course| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %></span>
          <p><%= course.name %></p>
        </div>
        <div class="card-action">
          <% if current_user && !current_user.courses.include?(course) %>
            <%= link_to "Enroll", courses_enroll_path(course_id: course.id), data: {
              turbo_method: :post
            }  %>
          <% end %>
          <%= link_to "View Course", course_path(course) %>
          <% if logged_in? %>
            <%= link_to "Edit Course", edit_course_path(course) %>
          <%end%>
        </div>
      </div>
    </div>
<% end %>

app/views/courses/_form.html.erb
<%= render 'shared/errors', obj: @course %>

<h2 class="center-align"><%= @course.new_record? ? 'Add Course' : 'Update Course' %></h2>
<%= form_for @course do |f| %>

  <%= f.label :short_name %>
  <%= f.text_field :short_name %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :dercription %>
  <%= f.text_area :description %>
  
  <% if @course.new_record? %>
    <%= f.submit "Add Course", class: 'waves-effect waves-light btn-small' %> 
  <% else %>
    <%= f.submit "Update Course", class: "waves-effect waves-light btn-small" %>
  <% end %>
<% end %>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<h2 class="center-align">All Courses</h2>
<div class="row">
  <%= render 'courses_list' %>
</div>

app/views/courses/new.html.erb
<%= render 'form' %>

app/views/courses/show.html.erb
<h2 class="center-align">Course Details</h2>
<div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= @course.short_name %></span>
        <p><%= @course.name %></p>
        <p><%= @course.description %></p>
      </div>
      <div class="card-action">
        <%= link_to "Edit Course", edit_course_path%>
      </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
        <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Tech University</h5>
                <p class="grey-text text-lighten-4">The future of development training</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Information</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2024 Tech University
            <a class="grey-text text-lighten-4 right" href="#!">About</a>
        </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key,msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_navbar.html.erb
<ul id="dropdown1" class="dropdown-content">
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
</ul>
<nav>
    <div class="container">
      <div >
        <%= link_to "Tech University", root_path, :class => "brand-logo" %>
        <ul class="right hide-on-med-and-down">
            <li><%= link_to "Add Course", new_course_path %></li>
            <li><%= link_to "Courses", courses_path %></li>
            <li><%= link_to "Students", students_path %></li>
            <% if !logged_in? %>
            <li><%= link_to "SignUp", new_student_path %></li>
            <li><%= link_to "Login", login_path %></li>
            <% end%>
            <li><%= link_to "Logout", logout_path, data: {
                      turbo_method: :delete
                    } %>
            </li>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tech University" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application","custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar"%>
    </header>
    <main>
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
    <footer class="page-footer">
      <%= render "layouts/footer"%>
    </footer>
  </body>
</html>

app/views/logins/new.html.erb
<h2 class="center-align" >Login</h2>
<%= form_for :login do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <%= f.submit "Login", class: 'waves-effect waves-light btn-small' %> 

<% end %>

app/views/pages/about.html.erb
<h2>I am About Page</h2>

app/views/pages/address.html.erb
<h2>I am Address Page</h2>

app/views/pages/contact.html.erb
<h2>I am Contact Page</h2>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="container">
    <div class="row">
        <div class="col s12 m12" >
            <div class="card-panel red lighten-2">
                <span class="white-text">
                    <strong> <%= pluralize(obj.errors.count, "error")%></strong>
                        <% obj.errors.full_messages.each do |msg| %>
                          <ul>
                            <li><%= msg %></li>
                          </ul>
                        <% end %>
                </span>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student%>

<h2 class="center-align"><%= @student.new_record? ? 'Sign Up' : 'Edit' %></h2>
<%= form_for @student do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  
  <% if @student.new_record? %>
    <%= f.submit "Add Student", class: 'waves-effect waves-light btn-small' %> 
  <% else %>
    <%= f.submit "Update Profile", class: "waves-effect waves-light btn-small" %>
  <% end %>
<% end %>

app/views/students/_students_list.html.erb
<% @students.each do |student| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= student.name %></span>
          <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="card-action">
          <%= link_to "Student Profile", student_path(student)%>
        </div>
      </div>
    </div>
<% end %>

app/views/students/index.html.erb
<h2 class="center-align"> All Students </h2>
<div class="row">
    <%= render 'students_list' %>
</div>

app/views/students/show.html.erb
<h2 class="center-align">Student Profile</h2>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= @student.name %></span>
          <p>Enrolled in :
            <% if @student.courses %>
              <% @student.courses.each do |course| %>
                <ul>
                  <li><%= course.name %></li>
                </ul>
              <% end %>
            <% else %>
                <%= "None"%>
            <% end %>
          </p>
        </div>
        <div class="card-action">
          <% unless current_user != @student %>
            <%= link_to "Edit Profile", edit_student_path%>
          <% end %>
        </div>
      </div>
    </div>

app/views/welcome/index.html.erb
<h1> Welcome page </h1>